feat: Update the doc with the stream payments integration
portittech/pay-with-toonie-doc pull request #9
Opened 2023-09-05 15:01 UTC by marco-kuama

2023-09-05 15:17 UTC, SimoneBressan requested changes

2023-09-05 15:17 UTC, SimoneBressan commented on .gitignore
> +.vscode
# Miscellaneous
.DS_Store

# IntelliJ related
*.iml
*.ipr
*.iws

2023-09-05 15:17 UTC, SimoneBressan commented on README.md
> +    console.log('userError', err)
```suggestion
    console.error('userError', err)
```

2023-09-06 06:19 UTC, kuamanet requested changes

2023-09-06 06:19 UTC, kuamanet commented on README.md
> +`options` is an object with some parameters:
```suggestion
`options` is an object with following properties:
```

2023-09-11 06:56 UTC, kuamanet approved these changes

2023-09-11 06:56 UTC, merged